variable "location" {
  type        = string
  description = "Azure region for all resources in this environment."
  default     = "southeastasia"
}

variable "resource_group_name" {
  type        = string
  description = "Resource group that holds the workload (different from the tfstate RG)."
  default     = "rg-commercial-trainning"
}

variable "name_prefix" {
  type        = string
  description = "Short prefix used for resource names. Lowercase, no special characters."
  default     = "commercial"
}

variable "enable_cosmos_free_tier" {
  type        = bool
  description = "Set to false if the subscription has already used its single free-tier slot."
  default     = true
}

variable "enable_grafana_alloy_sidecar" {
  type        = bool
  description = <<-EOT
    When true, auth-service, report-service, and data-ingest-service get a
    Grafana Alloy sidecar. The sidecar image must be the custom Alloy image
    built from monitoring/alloy so it listens for OTLP on localhost:4317/4318.
  EOT
  default     = true
}

variable "report_service_image" {
  type        = string
  description = "Override after pushing the real image to ACR."
  default     = "crcommerciala9be68.azurecr.io/report-service:latest"
}

variable "alloy_image" {
  type        = string
  description = "Grafana Alloy sidecar image. Must be overridden with the ACR image built from monitoring/alloy before enabling the sidecar."
  default     = "crcommerciala9be68.azurecr.io/alloy:latest"
}

variable "data_ingest_image" {
  type        = string
  description = "Override after pushing the real image to ACR."
  default     = "crcommerciala9be68.azurecr.io/data-ingest-service:latest"
}

variable "auth_service_image" {
  type        = string
  description = "Override after pushing the real image to ACR."
  default     = "crcommerciala9be68.azurecr.io/auth-service:latest"
}

variable "prometheus_image" {
  type        = string
  description = "Prometheus image. The CD workflow replaces this with the ACR image built from monitoring/prometheus."
  default     = "crcommerciala9be68.azurecr.io/prometheus:latest"
}

variable "grafana_image" {
  type        = string
  description = "Grafana image. The CD workflow replaces this with the ACR image built from monitoring/grafana."
  default     = "crcommerciala9be68.azurecr.io/grafana:latest"
}

variable "loki_image" {
  type        = string
  description = "Loki image used for log aggregation. Override with an ACR image if you build and pin Loki yourself."
  default     = "grafana/loki:latest"
}

variable "grafana_admin_user" {
  type        = string
  description = "Grafana admin username. The password is generated by Terraform and exposed as a sensitive output."
  default     = "admin"
}

variable "loki_url" {
  type        = string
  description = "Optional external Loki base URL. When null, Grafana and Alloy use the Loki Container App deployed by this stack."
  default     = null
}

variable "report_http_concurrent_requests" {
  type        = number
  description = "KEDA HTTP scaler threshold for report-service. Combined with min_replicas=0 the app scales to zero when idle and spins replicas up at this concurrency level."
  default     = 50
}

variable "ingest_unprocessed_event_threshold" {
  type        = number
  description = "KEDA azure-eventhub scaler threshold for data-ingest-service. Replicas are added as unprocessed events per partition exceed this count, and removed as the lag clears."
  default     = 64
}

variable "tags" {
  type = map(string)
  default = {
    Environment = "Training"
    ManagedBy   = "Terraform"
  }
}
